Added redirection for echo

diff --git a/processes_and_signals/6-stop_me_if_you_can b/processes_and_signals/6-stop_me_if_you_can
--- a/processes_and_signals/6-stop_me_if_you_can
+++ b/processes_and_signals/6-stop_me_if_you_can
@@ -6,9 +6,9 @@ pass="0 One or more processes matched the criteria"
 fail="1 No processes matched"
 if [ $status == 0 ]
 then
-    echo "$pass"
+    echo "$pass" >&2
 fi
 if [ $status == 1 ]
 then
-    echo "$fail"
+    echo "$fail" >&2
 fi
